ALTER TABLE bs.game ADD COLUMN created_at TIMESTAMP;
ALTER TABLE bs.game ADD COLUMN updated_at TIMESTAMP;

ALTER TABLE bs.player ADD COLUMN created_at TIMESTAMP;
ALTER TABLE bs.player ADD COLUMN updated_at TIMESTAMP;
