spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/bs
    username: user
    password: pass
  jooq:
    sql-dialect: postgres
#  flyway:
#    url: jdbc:postgresql://localhost:5433/bs
#    user: user
#    password: pass

management:
  endpoints:
    web:
      exposure:
        include: 'health,info,metrics'
